services:
  postgres:
    image: postgres:15-alpine
    container_name: hospital-postgres
    restart: always
    environment:
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_password
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: hospital-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hospital.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
